### ISSUE TITLE
Sound transcriber error or bug

### ISSUE THREAD

**Issue by hassan594** [tecwindow/SoundTranscriber#1]
Hello.
  I run this program and look this error:
  OnInit returned false, exiting...
  Why?
  SoundTranscriber version 1.3.2 has been installed on my system.
  v1.1 gived python error.
  What i should to do?

**Comment by MesterPerfect** [comment]
Could you please include the complete error message? Additionally, let me know if you downloaded the software from the GitHub repository or installed it using Winget.

**Comment by MesterPerfect** [comment]
@MesterPerfect test

**Comment by MesterPerfect** [comment]
@hassan594 Could you please include the complete error message? Additionally, let me know if you downloaded the software from the GitHub repository or installed it using Winget.

**Comment by hassan594** [comment]
Hello.
  This is an image from error.
  Sound transcriber v1.3.2 has been installed on my system.
  This version was working; but soddenly last run gived this error.
  Thanks for your quick help.

**Comment by hassan594** [comment]
Yeh. I download this program from githup.
Ofcourse, this program downloaded from tekwindow and telegram persian channel.

**Comment by MesterPerfect** [comment]
> Hello. This is an image from error. Sound transcriber v1.3.2 has been installed on my system. This version was working; but soddenly last run gived this error. Thanks for your quick help.



@hassan594 It seems that the image was not embedded correctly, causing it not to appear in your comment.
 This issue may arise when attempting to run the Sound Transcriber multiple times. To avoid this problem, please ensure it doesn't happen and try running it again. If the error persists, please inform me.

**Comment by MesterPerfect** [comment]
> Yeh. I download this program from githup. Ofcourse, this program downloaded from tekwindow and telegram persian channel.


@hassan594 That's fine, you can install it using winget via command line
```
winget install --id=tecwindow.soundTranscriber -e
```

**Comment by hassan594** [comment]
cx_Freeze: Application Terminated  OnInit returned false, exiting... Sent from Mail for Windows From: AhmedBakrSent: ‏چهارشنبه,‏ ‏22 ‏آذر ‏1402 ‏11:37 ‏ب.ظTo: tecwindow/SoundTranscriberCc: hassan594; MentionSubject: Re: [tecwindow/SoundTranscriber] Sound transcriber error or bug (Issue ***@***.*** That's fine, you can install it using winget via command linewinget install --id=tecwindow.soundTranscriber -e—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by hassan594** [comment]
Yeh. I download this program from githup.
Ofcourse, this program downloaded from tekwindow and telegram persian channel.
![screenshot_14-12-2023_08-46-40](https://github.com/tecwindow/SoundTranscriber/assets/60962760/65584e53-116f-4c40-825b-daafb92ac87e)
This is an error from command line.

Microsoft Windows [Version 10.0.19045.3693]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Bab>winget install --id=tecwindow.soundTranscriber -e
No package found matching input criteria.

**Comment by MesterPerfect** [comment]
@hassan594 The picture does not match the message you wrote. The image indicates that the program was found and installed successfully. Additionally, it reveals that Sound Transcriber v1.0.0 is installed, whereas the first version added to Winget is version 1.2. Please try using the code again, ensuring attention to the correct usage of lowercase and uppercase letters.

winget install --id=tecwindow.SoundTranscriber -e

**Comment by hassan594** [comment]
Hello and happy for you.
Now, the program is working successfully.
I run your command and reinstall program and issue fixed.
But I'm worry for next error or bugs for converting.
Thanks.

**Comment by hassan594** [comment]
Does this program can convert multi files at next?

**Comment by MesterPerfect** [comment]
> Hello and happy for you. Now, the program is working successfully. I run your command and reinstall program and issue fixed. But I'm worry for next error or bugs for converting. Thanks.
  
Hello,

If you encounter any errors during the conversion process, please open an issue and submit it to us for resolution.
Be sure to include the log file of the program, which you can access within the program through the File menu. Alternatively, you can open the log file directly by entering the following path: ```%appdata%\tecwindow\SoundTranscriber```

**Comment by MesterPerfect** [comment]
> Does this program can convert multi files at next?

We plan to incorporate this feature in future updates.

**Comment by hassan594** [comment]
Hello.
  Is it possible to incorporate this future in sound transcriber?
  Audio recording for life transcribtion.
  Thanks.

**Comment by MesterPerfect** [comment]
@hassan594 We plan to incorporate this feature in future updates.
