### ISSUE TITLE
@hassan594 We plan to incorporate this feature in future updates.

### ISSUE THREAD

**Issue by hassan594** [tecwindow/SoundTranscriber#2]
@hassan594 We plan to incorporate this feature in future updates.

_Originally posted by @MesterPerfect in https://github.com/tecwindow/SoundTranscriber/issues/1#issuecomment-1862666663_

**Comment by hassan594** [comment]
![Error](https://github.com/tecwindow/SoundTranscriber/assets/60962760/ed8e96e2-0887-4c31-b2ca-7ec7e6d17e72)

**Comment by MesterPerfect** [comment]
We haven't identified this error, and there have been no reports from other users. Therefore, we will address it only if it becomes widespread among users, accompanied by detailed information explaining the reasons for its occurrence.
